[tool.pylint."MESSAGES CONTROL"]
disable = [
    "line-too-long",
    "too-few-public-methods",
    "logging-fstring-interpolation",
    "too-many-arguments",
    "protected-access",
    "too-many-positional-arguments",
    "W0718"
]
