name: Workflow Main
on: 
  workflow_call:
    secrets:
      ACCOUNT_ID:
        required: true
      AWS_DEFAULT_REGION:
        required: false
      ECR_PROJ_NAME:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      TF_LOG:
        required: false
      IMAGE_TAG:
        required: false
      TF_WORKING_DIR:      
        required: false
      BASE_TF_WORKING_DIR:      
        required: false
      SNS_EMAIL_SUBSCRIBED:
        required: true

jobs:

  PrepareEnviromnentForTests:
    uses:  ./terraform_docker_local.yaml
    secrets:
      TF_LOG: ${{ secrets.TF_LOG || 'OFF' }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      IMAGE_TAG: ${{ secrets.IMAGE_TAG || 'latest' }}
      TF_WORKING_DIR: ${{ secrets.BASE_TF_WORKING_DIR || './base_terraform' }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      SNS_EMAIL_SUBSCRIBED: ${{ secrets.SNS_EMAIL_SUBSCRIBED}}

  ContinuousIntegration:
    uses: ./.github/workflows/pylint_and_pytest.yaml
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: [PrepareEnviromnentForTests]

  ContinuousDelivery:
    uses: ./.github/workflows/bp_base.yaml
    secrets:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ECR_PROJ_NAME: ${{ secrets.ECR_PROJ_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      IMAGE_TAG: ${{ secrets.IMAGE_TAG || 'latest' }}
    needs: [ContinuousIntegration]

  ContinuousDeployment:
    uses:  ./.github/workflows/terraform_docker_local.yaml
    secrets:
      TF_LOG: ${{ secrets.TF_LOG || 'OFF' }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      IMAGE_TAG: ${{ secrets.IMAGE_TAG || 'latest' }}
      TF_WORKING_DIR: ${{ secrets.TF_WORKING_DIR || './terraform' }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      SNS_EMAIL_SUBSCRIBED: ${{ secrets.SNS_EMAIL_SUBSCRIBED}}
    needs: [ContinuousDelivery]
