name: CI/CD Pipeline Brewerie Data Lake
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  BrewerieDataLakePipeline:
    uses: ./.github/workflows/cicd_lint_and_bp_and_tf.yaml
    secrets:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}
      ECR_PROJ_NAME: brewerie_data_lake
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_LOG: 'OFF'
      IMAGE_TAG: '1.0.0'
      TF_WORKING_DIR: './terraform'
      BASE_TF_WORKING_DIR: './base_terraform'
      SNS_EMAIL_SUBSCRIBED: ${{ secrets.SNS_EMAIL_SUBSCRIBED }}